#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026, Hewlett Packard Enterprise Development LP
#
#
# obj_ndctl_sds/TEST0 -- check if the shutdown-state-related code is not run when no PMem is in use.
#                        DAOS-18296
#

. ../unittest/unittest.sh

require_fs_type non-pmem
require_ndctl_enable
require_test_type short

setup

FILE=$DIR/testfile

# obj_ndctl_sds commands
CREATE=c
OPEN=o

expect_normal_exit obj_ndctl_sds $FILE $CREATE

expect_normal_exit obj_ndctl_sds $FILE $OPEN

check

pass
